config/routes.rb
Rails.application.routes.draw do

  post 'public_figures/preview' => 'public_figures#preview', as: :public_figure_preview
  get '/templates' => 'public_figures#templates', as: :public_figure_templates
  resources :public_figures 

  resources :users

  root 'public_figures#new'

  resources :aggregators, only: [:index, :new] 
  post '/aggregators/fb-id-from-string' => 'aggregators#fb_id_from_string'
  post '/aggregators/insta-id-from-string' => 'aggregators#insta_id_from_string'
  

end

app/models/public_figure.rb
class PublicFigure < ActiveRecord::Base

  attr_accessor :validation_keys

  def update_media(media_hash)
    new_media_to_return = {
      'tweets': [],
      'instas': []
    }
    media_hash.each do |social_network_key, posts|
      my_key = media_keys_map[social_network_key]
      posts.each do |post|
        if post[:created_at] >= self.updated_at
          new_media_to_return[my_key] << post
        end
      end

      # at this point we are not saving ANY backlog of posts, only N most recent of any social network posts 

      self[social_network_key] = posts
    end

    self.save
    new_media_to_return
  end

  private

  def media_keys_map
    {
      'most_recent_tweets': :tweets,
      'most_recent_instagrams': :instas
    }
  end
    

end

app/controllers/public_figures_controller.rb
class PublicFiguresController < ApplicationController
  layout 'public_figures', only: :show
  layout 'iframes', only: :new

  def new
    headers['X-Frame-Options'] = 'ALLOWALL'
    @pf = PublicFigure.new
    @user = User.new
  end

  def create
    @pf = PublicFigure.new(pf_params)
    if @pf.save
      aggregate_to_thumbnails_json
      redirect_to public_figure_path(@pf)
    else
      render :new
    end
  end

  def show
    if params[:id]
      @pf = PublicFigure.find(params[:id])
    else
      @pf = PublicFigure.find_by(display_name: 'The Mechanism')
    end

    respond_to do |format|
      format.html 
      format.json { render :json => @pf.to_json }
    end
  end

  def update
    @pf = PublicFigure.find(params[:id])

    # json requests containing the :updated_at key are requests for an updated aggregate feed.
    # ensure 10 minute intervals between aggregate requests to 3rd parties
    if verify_time(pf_params[:updated_at])
      a = Aggregator.new(@pf)
      @new_media = @pf.update_media(a.social_media)
    end
    
    respond_to do |format|
      format.json { 
        render json: @new_media.to_json
      }
    end
  end

  def preview
    p '#'*80
    p 'params check'
    p "#{params.inspect}"
    p '#'*80
    p 'pf_params check'
    p "#{pf_params.inspect}"
    @pf = PublicFigure.new(pf_params)
    agatha = Aggregator.new(@pf)
    render json: agatha.social_media.to_json
  end

  def templates 
    render json: {
      insta: (render_to_string '/public_figures/insta_lodash_temp', layout: false),
      tweet: (render_to_string '/public_figures/tweet_lodash_temp', layout: false)
    }
  end

  private

  def pf_params
    params.require(:public_figure).permit(:display_name, :facebook_id, :twitter_handle, :twitter_search_terms, :instagram_id, :instagram_search_tags, :updated_at)
  end

  def verify_time(iso_string)
    unless iso_string
      return false
    end
    last_updated = Time.new(iso_string)
    now = Time.new
    now - last_updated >= 10.minutes
  end

  def aggregate_to_thumbnails_json
    begin
      agatha = Aggregator.new(@pf)
      @pf.update_media(agatha.social_media)
    rescue => e
      {errors: e} 
    end
  end

end

app/helpers/public_figures_helper.rb
module PublicFiguresHelper

  # def label_template(display_text)
  #   html = '<a href="#"><i class="fa fa-minus-circle" data="toggle-active"></i></a> ' + display_text + ' <i class="fa fa-question-circle"></i>'
  #   html.html_safe
  # end

  def label_template( hash )
    expandable = hash[:expand] ? expand_contract_field_popover( hash[:expand] ) : ''
    q_n_a = question_n_answer_popover( hash[:q_n_a] )
    html = expandable + hash[:display_text] + q_n_a
    html.html_safe
  end

  def id_check_label( hash ) # same hash format as above -- but adds id helper
    html = label_template(hash)
    id_check =  ' <button data="test-username" type="' + hash[:id_type] + '" class="btn btn-default btn-xs">Get Page ID</button></br>'
    html += id_check.html_safe
  end

  def question_n_answer_popover( q_n_a )
    wrap_with_popover( q_n_a, ' <i class="fa fa-question-circle"></i>' )
  end

  def expand_contract_field_popover( expand )
    wrap_with_popover({
        title: 'Click to remove this from your search.',
        placement: 'left',
        content: ''
      },
      ' <a href="#"><i class="fa fa-minus-circle" data="toggle-active"></i></a> ' )
  end

  def wrap_with_popover( hash, string_to_wrap )
    # title_placement_content_form_input
    html = '<span data-toggle="popover"' +
      ' title="' + hash[:title]  + '" ' +
      ' data-placement="' + hash[:placement] + '"' +
      'data-content="' + hash[:content]  + '"' +
      '>' + string_to_wrap +
      '</span>' 
    html.html_safe
  end


end

app/views/public_figures/_preview_form_with_popovers.html.erb
<!-- 
  
  DEV NOTES:
  helper functions in form defined in helpers/public_figures_helper 

  simple form gem DSL needs augmentation here, with custom icons, buttons, and popover fuctionality with each form element. 

  so - using simple_form conventions, but in 'label' field, defined helper html formatting options
  tried to be as straight-forward with indentation and intention here

  JavaScript note ->
  embedded in each form element is a data-key attribute
  this gives:
    - expected data type of field for client side validation
    - validation url if server call is needed for validation

    heirarchy is - FormCtrl holds an instance of RealTimeValidator , check
      - assets/js/public_figures/utils/realTimeValidator
      - assets/js/public_figures/DOMcomponents/socialMediaFormController

-->

<%= simple_form_for pf do |f| %>

  <!-- < %= f.input :display_name, 
      label: label_template({
        expand: false,
        display_text: 'Display Name',
        q_n_a: 
          {
            title: 'Enter the Display Name of the entity you want to query.',
            placement: 'right',
            content: 'Enter the human-readable name of your search entity here.'
          }
      })  
  %> -->


  <script type="text/template" id="form-status-icons">
    <div data-key="valid">
      <i class="fa fa-check-circle"></i>
    </div>
    
    <div data-key="invalid">
      <i class="fa fa-exclamation-circle"></i>
    </div>
    
    <div data-key="waiting">
      <i class="fa fa-refresh icon-refresh-animate"></i>
    </div>

    <div data-key="select">
      <a href="#"><i class="fa fa-expand fa-pulse"></i></a>
    </div>

  </script>
  <table>
    <tr>
      <!-- TODO -- REFACTOR THE TABLE WRAPPER TO ANOTHER HELPER METHOD -->
      <td class="col-md-3">
        <%= f.error :facebook_id %>
        <%= f.input :facebook_id,
            input_html: {
              'data-key': {
                type_requirement: 'number',
                validate_url: 'foobar.com'
              }.to_json
            }, 
            label: label_template({
              expand: true,
              display_text: 'Facebook Page ID',
              q_n_a: 
                {
                  title: 'Facebook timeline query',
                  placement: 'bottom',
                  content: 'We need to find your chosen page by Facebook ID number. If you don\'t know what your number is, we can search for it. Just type the page name in this field, and click \'Get Page ID\''
                }
            })  
        %>
      </td>
      <td class="col-md-1">
           
      </td>
    </tr>
    <tr>
      <td class="col-md-3">
        <%= f.input :twitter_handle,
            input_html: {
              'data-key': {
                type_requirement: 'string',
                validate_url: 'foobar.com'
              }.to_json
            }, 
            label: label_template({
              expand: true,
              display_text: 'Twitter Handle',
              q_n_a: 
                {
                  title: 'Twitter handle help',
                  placement: 'bottom',
                  content: 'Enter the twitter username or handle that you\'d like to search.'
                }
            })  
        %>
      </td>
      <td class="col-md-1">
        
      </td>
    </tr>
    <tr>
      <td class="col-md-3">
        <%= f.input :twitter_search_terms,
            input_html: {
              'data-key': {
                type_requirement: 'string#csv'
              }.to_json
            }, 
            label: label_template({
              expand: true,
              display_text: 'Twitter search terms',
              q_n_a: 
                {
                  title: 'Twitter search terms',
                  placement: 'bottom',
                  content: 'Want to search for specific phrases on Twitter? Enter each search term separated by a comma.'
                }
            })  
        %>
      </td>
      <td class="col-md-1">
        
      </td>
    </tr>
    <tr>
      <td class="col-md-3">
        <%= f.input :instagram_id,
            input_html: {
              'data-key': {
                type_requirement: 'number',
                validate_url: 'foobar.com'
              }.to_json
            }, 
            label: label_template({
              expand: true,
              display_text: 'Instagram Username',
              q_n_a: 
                {
                  title: 'Instagram Username',
                  placement: 'bottom',
                  content: 'Some Instagram usernames aren\'t what you expect. Want to test a username before a search? Enter the text here and press \'Get Instagram ID\''
                }
            })  
        %>
      </td>
      <td class="col-md-1">
        
      </td>
    </tr>
    <tr>
      <td class="col-md-3">
        <%= f.input :instagram_search_tags,
            input_html: {
              'data-key': {
                type_requirement: 'string#csv'
              }.to_json
            }, 
            label: label_template({
              expand: true,
              display_text: 'Instagram search terms',
              q_n_a: 
                {
                  title: 'Instagram search terms',
                  placement: 'top',
                  content: 'Want to search for Instagrams tagged with specific hashtags? Enter each tag separated by a comma.'
                }
            })  
        %>
      </td>
      <td class="col-md-1">
        
      </td>
    </tr>

  </table>

  






 
  
  
  
  
 
  

  <div class='btn btn-primary' data='preview'>Preview</div>
  

  <!-- currently not actually submitting to DB, only handing off for social media queries without save -->
  <!-- so - for semantic reasons, no submit button. only preview -->

<% end %>

app/views/public_figures/_preview_modal_contents.html.erb
<script type="text/template" data-modal-contents="user#new">
  <div id='solicit'>
  	You're playing with <strong>The Social Mechanism</strong>, a social media aggregator developed by us.
  	<a href="http://www.themechanism.com/" target="_blank"><%= image_tag("TheMech_Logo2.png") %></a> 
  	<br>
  	<%= render 'users/new', user: @user %> 
  </div>
</script>

<script type="text/template" data-modal-contents="thanks-for-submission">
  <div>
  	<h3>Enjoy the Social Mechanism!</h3>
		<h4>And thanks for staying in touch!</h4>
  </div>
</script>

<script type="text/template" data-modal-contents="user#error">
  <div id='validationErrors'>
  	<h4>Seems like you forgot to include your <span class='form-errors'></span>.</h4>
  	<a class='btn btn-warning'>One more time!</a>
  </div>
</script>

app/views/public_figures/_uncollapse_button.html.erb
<div id="collapsed-form" class="row">
  <div 
    class='btn btn-primary col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4' 
    data='unCollapse'>
    Redo query terms?
  </div>
</div>

app/views/public_figures/new.html.erb
<div class="pad-the-nav"></div>

<%= render 'uncollapse_button' %>

<%= render 'preview_form_with_popovers', pf: @pf %>

<div class="masonryGrid">
</div>


<script>
  $(document).ready(function () {

    var PATHS = {
      preview: '<%= public_figure_preview_path  %>',
      templates: '<%= public_figure_templates_path %>',
      'public_figure[facebook_id]': '<%= aggregators_fb_id_from_string_path %>',
      'public_figure[instagram_id]': '<%= aggregators_insta_id_from_string_path %>'
    };
    
    // global for the time being - ease of debugging
    window.PPM = new PreviewPageMaster(PATHS);
  });
  
    
</script>

<script type="text/template" id="waiting-icon">
  <%= render 'shared/animated_refresh_icon' %>
</script>


<%= render 'shared/bootstrap_modal' %>  

<%= render 'preview_modal_contents' %>

app/views/public_figures/show.html.erb
<div class="pad-the-nav"></div>

<div class="masonryGrid">
  <!-- < %= render 'thumbnails', pf: @pf%> -->
</div>

<script>
  var PATHS = {
    publicFigure: "<%= public_figure_path(@pf) %>",
    templates: "<%= public_figure_templates_path(@pf) %>"
  }
  $(document).ready(function(){
    var SMTC = new SocialMediaThumbnailController(PATHS);
    // window.SQM = SQM;
    SMTC.init();
  });
</script>